# This is a basic workflow to help you get started with Actions

name: node tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: node test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TEST: 1
      FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/emulator-cache

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "yarn"
          cache-dependency-path: "./mod/fastfire/yarn.lock"
      - run: npm install -g firebase-tools
      - run: npm ci

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ${{ env.FIREBASE_EMULATORS_PATH }}
          key: ${{ runner.os }}-firebase-emulators-${{
            hashFiles('./emulator-cache/**') }}
        continue-on-error: true

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('./node/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Fastfire
        working-directory: ./mod/fastfire
        run: npm i --global yarn && yarn install --prefer-offline && yarn build

      - name: Install dependencies
        working-directory: ./node
        run: pnpm i --frozen-lockfile

      - name: Run linting
        working-directory: ./node
        run: pnpm run lint

      - name: Run test SPEC
        working-directory: ./node
        run: pnpm run test

      - name: Run test API
        working-directory: ./node
        run: pnpm run emulator-test-api
